version: '3.8'

services:
  github-scripts:
    image: geertmeersman/github-scripts:latest
    container_name: github-scripts
    restart: unless-stopped
    environment:
      WEB_PORT: ${WEB_PORT}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_USER: ${GITHUB_USER}
      MERGE_METHOD: ${MERGE_METHOD}
      SMTP_USER: ${SMTP_USER}
      SMTP_PWD: ${SMTP_PWD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TO: ${EMAIL_TO}
      TELEGRAM_BOT_ID: ${TELEGRAM_BOT_ID}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    tty: true
    volumes:
      - ${LOG_VOLUME}:/var/log/github-scripts
